### ISSUE TITLE
Crash on application start

### ISSUE THREAD

**Issue by dmorn** [membraneframework/membrane_core#583]
On membrane_core `v0.12.6`, our pipielines are crashing with the following report
```
** (Mix) Could not start application pepe: Pepe.Application.start(:normal, []) returned an error: shutdown: failed to start child: Pepe.Pipeline
    ** (EXIT) exited in: GenServer.call(#PID<0.3583.0>, {Membrane.Core.Message, :start_utility, %{id: Membrane.Core.Stalker, start: {Membrane.Core.Stalker, :start_link, [%{ets: #Reference<0.401975344.1819934724.185538>}]}}, []}, 5000)
        ** (EXIT) an exception was raised:
            ** (KeyError) key :pid_string not found in: %{component_path: ["Pepe.Pipeline/"], component_type: :pipeline, is_name_provided: true, is_utility: true, log_metadata: [], name: "Pepe.Pipeline", name_string: "Pepe.Pipeline/", stalker: nil, utility_name: " subprocess supervisor"}
                (membrane_core 0.12.6) lib/membrane/core/stalker.ex:172: Membrane.Core.Stalker.register_name_for_stalker/1
                (membrane_core 0.12.6) lib/membrane/core/stalker.ex:130: Membrane.Core.Stalker.setup_process_local_observability/2
                (membrane_core 0.12.6) lib/membrane/core/subprocess_supervisor.ex:180: Membrane.Core.SubprocessSupervisor.handle_info/2
                (stdlib 4.2) gen_server.erl:1123: :gen_server.try_dispatch/4
                (stdlib 4.2) gen_server.erl:1200: :gen_server.handle_msg/6
                (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

This does not happen on `v0.12.5`.

**Comment by FelonEkonom** [comment]
Hi, you can use branch `release-0.12.6` of membrane_core or remove `:unsafely_name_processes_for_observer` config environment (because I guess, that you have set it) and recompile `:membrane_core`.

We will include a fix for your problem in the upcoming release `v0.12.7`, which should be published before the end of this week, or maybe even today.

**Comment by dmorn** [comment]
Thanks!

**Comment by FelonEkonom** [comment]
Fixed in https://github.com/membraneframework/membrane_core/releases/tag/v0.12.7
