### ISSUE TITLE
How to set up a Membrane Pipeline pt 1 -> Unit Tests are Failing 

### ISSUE THREAD

**Issue by michaelwa** [membraneframework/membrane_core#686]
Hello, 

I am going through the "How to set up a Membrane Pipeline pt 1"  https://membrane.stream/learn/basic_pipeline tutorial. I have made it successfully to the "Depeyloader" topic and two of the unit tests are failing. 

```
  1) test Depayloader should assemble the packets and form a frame (with membrane's testing framework based on generator) (DepayloaderTest)
     test/elements/depayloader_test.exs:40
     ** (EXIT from #PID<0.1261.0>) an exception was raised:
         ** (Membrane.ParentError) Cannot start child :source,               reason: {:function_clause,
      [
        {String, :valid?, [:source, :default], [file: ~c"lib/string.ex", line: 1827]},
        {Membrane.Core.Element, :init, 1,
         [file: ~c"lib/membrane/core/element.ex", line: 112]},
        {:gen_server, :init_it, 2, [file: ~c"gen_server.erl", line: 962]},
        {:gen_server, :init_it, 6, [file: ~c"gen_server.erl", line: 917]},
        {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}
      ]}
             (membrane_core 0.8.1) lib/membrane/core/parent/child_life_controller/startup_handler.ex:198: Membrane.Core.Parent.ChildLifeController.StartupHandler.start_child/5
             (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
             (membrane_core 0.8.1) lib/membrane/core/parent/child_life_controller.ex:42: Membrane.Core.Parent.ChildLifeController.handle_spec/2
             (membrane_core 0.8.1) lib/membrane/core/pipeline/action_handler.ex:63: Membrane.Core.Pipeline.ActionHandler.do_handle_action/4
             (membrane_core 0.8.1) lib/membrane/core/pipeline/action_handler.ex:30: Membrane.Core.Pipeline.ActionHandler.handle_action/4
             (bunch 1.3.0) lib/bunch/enum.ex:121: anonymous fn/3 in Bunch.Enum.try_reduce/3
             (elixir 1.15.7) lib/enum.ex:4830: Enumerable.List.reduce/3
             (elixir 1.15.7) lib/enum.ex:2564: Enum.reduce_while/3
             (membrane_core 0.8.1) lib/membrane/core/callback_handler.ex:155: Membrane.Core.CallbackHandler.exec_handle_actions/5
             (stdlib 5.1.1) gen_server.erl:962: :gen_server.init_it/2
             (stdlib 5.1.1) gen_server.erl:917: :gen_server.init_it/6
             (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3

  2) test Depayloader should assemble the packets and form a frame (with membrane's testing framework) (DepayloaderTest)
     test/elements/depayloader_test.exs:14
     ** (EXIT from #PID<0.1265.0>) an exception was raised:
         ** (Membrane.ParentError) Cannot start child :source,               reason: {:function_clause,
      [
        {String, :valid?, [:source, :default], [file: ~c"lib/string.ex", line: 1827]},
        {Membrane.Core.Element, :init, 1,
         [file: ~c"lib/membrane/core/element.ex", line: 112]},
        {:gen_server, :init_it, 2, [file: ~c"gen_server.erl", line: 962]},
        {:gen_server, :init_it, 6, [file: ~c"gen_server.erl", line: 917]},
        {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}
      ]}
             (membrane_core 0.8.1) lib/membrane/core/parent/child_life_controller/startup_handler.ex:198: Membrane.Core.Parent.ChildLifeController.StartupHandler.start_child/5
             (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
             (membrane_core 0.8.1) lib/membrane/core/parent/child_life_controller.ex:42: Membrane.Core.Parent.ChildLifeController.handle_spec/2
             (membrane_core 0.8.1) lib/membrane/core/pipeline/action_handler.ex:63: Membrane.Core.Pipeline.ActionHandler.do_handle_action/4
             (membrane_core 0.8.1) lib/membrane/core/pipeline/action_handler.ex:30: Membrane.Core.Pipeline.ActionHandler.handle_action/4
             (bunch 1.3.0) lib/bunch/enum.ex:121: anonymous fn/3 in Bunch.Enum.try_reduce/3
             (elixir 1.15.7) lib/enum.ex:4830: Enumerable.List.reduce/3
             (elixir 1.15.7) lib/enum.ex:2564: Enum.reduce_while/3
             (membrane_core 0.8.1) lib/membrane/core/callback_handler.ex:155: Membrane.Core.CallbackHandler.exec_handle_actions/5
             (stdlib 5.1.1) gen_server.erl:962: :gen_server.init_it/2
             (stdlib 5.1.1) gen_server.erl:917: :gen_server.init_it/6
             (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3

.
Finished in 0.07 seconds (0.00s async, 0.07s sync)
3 tests, 2 failures
```
I have run a delta of my code the the template/end code:

`git diff template/end..template/start 
`
Which only shows that I have a "\n" in the wrong location: 
```
diff --git a/lib/elements/Depayloader.ex b/lib/elements/depayloader.ex
similarity index 100%
rename from lib/elements/Depayloader.ex
rename to lib/elements/depayloader.ex
index e343b32..db89180 100644
--- a/lib/elements/Depayloader.ex
+++ b/lib/elements/depayloader.ex
@@ -3,10 +3,10 @@ defmodule Basic.Elements.Depayloader do
   Element responsible for assembling the frames out of ordered packets.
   """
   use Membrane.Filter
+
   alias Basic.Formats.{Frame, Packet}
 
   def_input_pad(:input, demand_unit: :buffers, caps: {Packet, type: :custom_packets})
-
   def_output_pad(:output, caps: {Frame, encoding: :utf8})
 
   def_options(
```

When I compiled the template/end code it got a "mix.lock" error that said I needed to update my dependencies. There was no .tool-versions file defined in the cloned repo. I am running:  

```
❯ asdf current
elixir          1.15.7-otp-26   /home/<profile_folder>/.tool-versions
erlang          26.1.2          /home/<profile_folder>/.tool-versions
```

I failed to mention that 'template/end' fails with the same errors.  The only tangible difference is the mix.lock update that I did. 

I was going to open an issue in the tutorial repository but it said to create issue in "membrane_core".

Many thanks in advanced!

**Comment by mat-hek** [comment]
The tutorial should be up to date for some time already, so I'm closing this. Please reopen or open another issue in case of further problems ;)
