### ISSUE TITLE
[bundlex] ElixirLS raises an exception in mix.exs

### ISSUE THREAD

**Issue by Noarkhh** [membraneframework/membrane_core#827]
ElixirLS raises the following in mix.exs file

```
an exception was raised:
    ** (FunctionClauseError) no function clause matching in Keyword.keys/1
        (elixir 1.16.3) lib/keyword.ex:643: Keyword.keys(nil)
        (bundlex 1.5.1) lib/bundlex/project.ex:196: Bundlex.Project.load/1
        (bundlex 1.5.1) lib/bundlex/project.ex:175: Bundlex.Project.get/1
        (unifex 1.2.0) lib/unifex/code_generator.ex:31: Unifex.CodeGenerator.get_generators/1
        (unifex 1.2.0) lib/unifex/code_generator.ex:22: Unifex.CodeGenerator.generate_code/1
        (unifex 1.2.0) lib/tasks/compile_unifex.ex:19: anonymous fn/1 in Mix.Tasks.Compile.Unifex.run/1
        (elixir 1.16.3) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
        (mix 1.16.3) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
```

**Comment by darthez** [comment]
Seems like with the current LSP work it might not be relevant anymore.
