### ISSUE TITLE
`membrane_h264_ffmpeg_plugin` crashes using Encoder profile `:constrained_baseline`

### ISSUE THREAD

**Issue by olegokunevych** [membraneframework/membrane_core#892]
While testing different Encoder profiles, found out that `:constrained_baseline` crashes pipeline.
However other profiles doesn't crash entire pipeline.

#### Pipeline example:

```
child(:source, %Membrane.RTMP.SourceBin{
  client_ref: state.client_ref
})
|> via_out(:video)
|> child(:video_parser, %Membrane.H264.Parser{
  output_alignment: :au,
  output_stream_structure: :annexb,
})
|> child(:h264_decoder, %Membrane.H264.FFmpeg.Decoder{})
|> child(:h264_encoder, %Membrane.H264.FFmpeg.Encoder{
  profile: :constrained_baseline
})
|> child(:output_video_parser, %Membrane.H264.Parser{
  output_alignment: :nalu,
  output_stream_structure: :annexb,
  repeat_parameter_sets: true
})
```

#### Actual result:

```
12:22:57.245 [error] pid=<0.899.0> mfa=Membrane.Core.Element.handle_info/2  <0.854.0>/{:endpoint, "63555e37-bd5b-4062-b08d-b1573536841b"}/:h264_encoder Error occured in Membrane Element:
** (RuntimeError) Failed to create native encoder: :codec_open
    (membrane_h264_ffmpeg_plugin 0.32.3) lib/membrane_h264_ffmpeg/encoder.ex:213: anonymous fn/1 in Membrane.H264.FFmpeg.Encoder.handle_stream_format/4
    (membrane_core 1.1.1) lib/membrane/core/callback_handler.ex:139: Membrane.Core.CallbackHandler.exec_callback/4
    (membrane_core 1.1.1) lib/membrane/core/callback_handler.ex:69: Membrane.Core.CallbackHandler.exec_and_handle_callback/5
    (membrane_core 1.1.1) lib/membrane/core/element/stream_format_controller.ex:82: Membrane.Core.Element.StreamFormatController.exec_handle_stream_format/4
    (membrane_core 1.1.1) lib/membrane/core/element.ex:237: Membrane.Core.Element.handle_info/2
    (stdlib 5.2) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

#### Expected result:

Pipeline works with all profiles described in the doc https://hexdocs.pm/membrane_h264_format/0.6.1/Membrane.H264.html#t:profile/0

**Comment by gBillal** [comment]
Actually the `H264` format defines the set of possible profiles, it doesn't mention that all of them should be supported by the encoder. The `x264` library used by `ffmpeg` (used in its turn by `membrane_h264_ffmpeg_plugin`) does not support `constrained_baseline` profile.
